version: "0.0.1"
support: wgsl
resources:
pipelines:
  sky_scatter:
    geometry: @geo_sky_scatter
    output: [@framebuffer_texture]
    clear: true
    push_constants:
      0: @pc_environment_data
    bind_groups:
      0:
        0: @mat4_mvp
  sky_fog:
    geometry: @geo_sky_fog
    output: [@framebuffer_texture]
    push_constants:
      0: @pc_environment_data
    bind_groups:
      0:
        0: @mat4_projection
        1: @mat4_view
        2: @mat4_model
  stars:
    geometry: @geo_sky_stars
    output: [@framebuffer_texture]
    blending: color_add_alpha_blending
    push_constants:
      0: @pc_environment_data
    bind_groups:
      0: @mat4_projection
      1: @mat4_view
      2: @mat4_model
  sun_moon_cycle:
    geometry: @geo_sun_moon
    output: [@framebuffer_texture]
    blending: color_add_alpha_blending
    push_constants:
      0: @pc_environment_data
    bind_groups:
      0: @mat4_projection
      1: @mat4_view
      2: @mat4_model
      3: @texture_sky_sun
      4: @texture_sky_moon
  terrain:
    geometry: @geo_terrain
    depth: @framebuffer_depth
    output: [@framebuffer_texture]
    blending: premultiplied_alpha_blending
    push_constants:
      0: @pc_chunk_position
      12: @pc_framebuffer_size
    bind_groups:
      0: @tex_block_atlas
      1: @ssbo_chunk_vertices
      2: @ssbo_chunk_indices
      3: @tex_electrum_lightmap
      4: mvp_mat4
  entity:
    geometry: @geo_entities
    depth: @framebuffer_depth
    output: [@framebuffer_texture]
    push_constants:
      0: @pc_parts_per_entity
    bind_groups:
      0: @bg_matrices
      1: @bg_entity
  electrum_gui:
    geometry: @geo_electrum_gui
    output: [@framebuffer_texture]
#    blending: premultiplied_alpha_blending
    bind_groups:
      0: @electrum_mat4
      1: @electrum_gl_texture